name: "Greet"
description: "Greet a user"
inputs:
  name:
    description: "Name to greet"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - run: python ${{ github.action_path }}/greet.py "${{ inputs.name }}"
      shell: bash
