name: Install Vjer
description: Installs the Vjer CI/CD tool
inputs:
  use-local:
    description: Use local Vjer for the action
    default: "false"
  use-pypi-test:
    description: Use Test PyPi for the action
    default: "false"
  version:
    description: Version of Vjer to use for the action
    default: "latest"

runs:
  using: composite
  steps:
    - name: Install Vjer
      shell: bash
      run: python "${{ github.action_path }}/action.py" "${{ inputs.version }}" "${{ inputs.use-local }}" "${{ inputs.use-pypi-test }}"
