name: Build Documentation
description: Build the documentation using Sphinx

runs:
  using: composite
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install docs dependencies
        shell: bash
        run: |
          PIP_OPTS="--upgrade --upgrade-strategy eager --root-user-action=ignore --no-input --disable-pip-version-check"
          python -m pip install $PIP_OPTS pip
          pip install $PIP_OPTS setuptools wheel
          pip install $PIP_OPTS -e .[doc]

      - name: Build Sphinx docs
        shell: bash
        working-directory: docs
        run: |
          sphinx-apidoc --output-dir=. ../batcave
          make html
