name: Shared Install Test Action

on:
  workflow_call:
    inputs:
      # required inputs
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      test-action:
        required: true
        type: string
      # optional inputs
      test-dir:
        required: false
        type: string
        default: .

env:
  ARTIFACTS_DIR: artifacts
  VJER_ENV: development

jobs:
  install-test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}

      - name: Install Python module for testing
        if: inputs.os != 'windows-latest'
        run: pip install $pypi_install_arg $ARTIFACTS_DIR/*.whl

      - name: Install Python module for testing
        if: inputs.os == 'windows-latest'
        run: pip install $pypi_install_arg (Get-Item $env:ARTIFACTS_DIR\*.whl)

      - name: Test installed module
        run: cd ${{ inputs.test-dir }} && ${{ inputs.test-action }}
