name: Shared PyPi Publish Action

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      publish-mode:
        required: true
        type: string
      python-version:
        required: true
        type: string
      use-local-vjer:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

env:
  ARTIFACTS_DIR: artifacts

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.ARTIFACT_TOKEN }}
      - name: Install local vjer
        run: pip install $ARTIFACTS_DIR/*.whl
        if: inputs.use-local-vjer
      - name: Install vjer
        run: pip install vjer
        if: ${{ ! inputs.use-local-vjer }}
      - name: Prepare Git
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git pull
      - name: Publish to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ env.ARTIFACTS_DIR }}
        if: inputs.publish-mode == 'pre_release'
      - name: Run post-publish steps
        run: vjer ${{ inputs.publish-mode }}
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ env.ARTIFACTS_DIR }}
        if: inputs.publish-mode == 'release'
      - name: Upload released artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}
        if: inputs.publish-mode == 'release'

# cSpell:ignore pypi vjer
