on:
  workflow_call:
    inputs:
      install-test-action:
        type: string
      skip-pypi-test:
        type: boolean
        default: false
      test-os-list:
        type: string
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      test-python-versions:
        type: string
        default: '["3.14"]'
      update-changelog:
        type: boolean
        default: false
      vjer-local:
        type: boolean
        default: false
      vjer-version:
        type: string
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNIT_TEST_DIR: test_results

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.test-os-list) }}
        python-version: ${{ fromJSON(inputs.test-python-versions) }}
    steps:
      - name: Run Vjer test
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: test
          os: ${{ matrix.os }}
          pyproject-build: true
          python-version: ${{ matrix.python-version }}
          vjer-local: ${{ inputs.vjer-local }}
          vjer-version: ${{ inputs.vjer-version }}
        continue-on-error: true

      - name: Publish Linux Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          action_fail: true
          action_fail_on_inconclusive: true
          check_name: Test Results (${{ matrix.os }}, Python ${{ matrix.python-version }})
          files: "${{ env.UNIT_TEST_DIR }}/**/*.xml"

      - name: Publish MacOS Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: matrix.os == 'macos-latest'
        with:
          action_fail: true
          action_fail_on_inconclusive: true
          check_name: Test Results (${{ matrix.os }}, Python ${{ matrix.python-version }})
          files: "${{ env.UNIT_TEST_DIR }}/**/*.xml"

      - name: Publish Windows Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: matrix.os == 'windows-latest'
        with:
          action_fail: true
          action_fail_on_inconclusive: true
          check_name: Test Results (${{ matrix.os }}, Python ${{ matrix.python-version }})
          files: "${{ env.UNIT_TEST_DIR }}/**/*.xml"
    permissions:
      checks: write
      issues: write
      pull-requests: write

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run Vjer build
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: build
          os: ubuntu-latest
          pyproject-build: true
          vjer-local: ${{ inputs.vjer-local }}
          vjer-version: ${{ inputs.vjer-version }}

  install-test:
    needs: build
    uses: ./.github/workflows/install-test.yaml
    if: inputs.install-test-action != ''
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-action: ${{ inputs.install-test-action }}
      test-dir: tests
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.test-os-list) }}
        python-version: ${{ fromJSON(inputs.test-python-versions) }}

  update-changelog:
    runs-on: ubuntu-latest
    if: ${{ inputs.update-changelog && (github.actor != 'github-actions[bot]') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/')) }}
    needs: install-test
    steps:
      - name: Update Changelog
        uses: arisilon/shared-actions/.github/actions/update-changelog@released
        with:
          git-commit-token: ${{ secrets.RELEASE_TOKEN }}

  pre_release:
    if: (github.event_name != 'pull_request') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'feature/'))
    needs: install-test
    runs-on: ubuntu-latest
    environment: pre_release
    steps:
      - name: Run Vjer pre_release
        if: ${{ !inputs.skip-pypi-test }}
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: pre_release
          enable-git-commit: ${{ secrets.RELEASE_TOKEN }}
          os: ubuntu-latest
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          pyproject-build: true
          vjer-local: ${{ inputs.vjer-local }}
          vjer-version: ${{ inputs.vjer-version }}

  rc_release:
    if: (github.event_name != 'pull_request') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/'))
    needs: pre_release
    runs-on: ubuntu-latest
    environment: rc_release
    steps:
      - name: Run Vjer rc_release
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: pre_release
          enable-git-commit: ${{ secrets.RELEASE_TOKEN }}
          os: ubuntu-latest
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          pyproject-build: true
          vjer-local: ${{ inputs.vjer-local }}
          vjer-version: ${{ inputs.vjer-version }}
        env:
          VJER_CFG: vjer-rc.yml

  release:
    if: (github.event_name != 'pull_request') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/'))
    needs: pre_release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Run Vjer release
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: release
          enable-git-commit: ${{ secrets.RELEASE_TOKEN }}
          os: ubuntu-latest
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          pyproject-build: true
          vjer-local: ${{ inputs.vjer-local }}
          vjer-version: ${{ inputs.vjer-version }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update Changelog
        if: inputs.update-changelog
        uses: arisilon/shared-actions/.github/actions/update-changelog@released
        with:
          git-commit-token: ${{ secrets.RELEASE_TOKEN }}

# cSpell:ignore pyproject
