name: Shared Actions Release

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    if: (github.ref_name == 'main') || startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Run Vjer release action
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: release
          enable-git-commit: ${{ secrets.RELEASE_TOKEN }}
          os: ubuntu-latest
          skip-artifact-download: "true"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update Changelog
        uses: arisilon/shared-actions/.github/actions/update-changelog@released
        with:
          git-commit-token: ${{ secrets.RELEASE_TOKEN }}
          fix-release-tag: "released"
