name: Shared Test Action

on:
  workflow_call:
    inputs:
      shared-action-var:
        required: true
        type: number

jobs:
  var-test:
    runs-on: ubuntu-latest
    steps:
      - name: Show the variable
        run: echo ${{ inputs.shared-action-var }}
