name: Update Changelog

on:
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - CHANGELOG.md

permissions:
  contents: write

jobs:
  update-changelog:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Update Changelog
        uses: arisilon/shared-actions/.github/actions/update-changelog@released
        with:
          git-commit-token: ${{ secrets.RELEASE_TOKEN }}
          fix-release-tag: "released"
