name: Shared GitHub Action Jobs

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      use-flit:
        required: false
        type: boolean
        default: false
      vjer-env:
        required: false
        type: string
        default: development

env:
  ARTIFACTS_DIR: artifacts
  UNIT_TEST_DIR: unit_test_results

jobs:
  vjer:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
      - name: Install vjer
        run: pip install vjer
      - name: Run ${{ inputs.action }}
        run: vjer ${{ inputs.action}}
        env:
          VJER_USE_FLIT: ${{ inputs.use-flit }}
          VJER_ENV: ${{ inputs.vjer-env }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}
        if: inputs.action == 'build'

# cSpell:ignore vjer
