name: Shared Vjer Action

on:
  workflow_call:
    inputs:
      # required inputs
      action:
        required: true
        type: string
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      # optional inputs
      pyproject-build:
        type: string
      use-pypi-test:
        type: boolean
        default: false
      vjer-env:
        type: string
        default: development
      vjer-local:
        type: boolean
        default: false
      vjer-version:
        type: string

env:
  ARTIFACTS_DIR: artifacts
  UNIT_TEST_DIR: test_results
  VJER_BUILD_NUM: ${{ github.run_id }}

jobs:
  vjer:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
      - name: Install vjer
        run: |
          if [[ -n "${{ inputs.vjer-version }}" ]]; then install_version="==${{ inputs.vjer-version }}"; fi
          if [[ "${{ inputs.use-pypi-test }}" == "true" ]]; then pypi_test_option="--index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple"; fi
          pip install $pypi_test_option vjer$install_version
        if: ${{ ! inputs.vjer-local }}
      - name: Install local vjer
        run: pip install .
        if: inputs.vjer-local
      - name: Run ${{ inputs.action }}
        run: vjer ${{ inputs.action }}
        env:
          VJER_ENV: ${{ inputs.vjer-env }}
          VJER_PYPROJECT_BUILD: ${{ inputs.pyproject-build }}
      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UNIT_TEST_DIR }}-${{ inputs.os }}-${{ inputs.python-version }}
          path: ${{ env.UNIT_TEST_DIR }}
        if: inputs.action == 'test'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_DIR }}
          path: ${{ env.ARTIFACTS_DIR }}
        if: inputs.action == 'build'

# cSpell:ignore pyproject
